name: Docker Image CI/CD

on:
  workflow_dispatch:   #manual run

jobs:
  # --- Job 1: Build and Push Images ---
  build:
    name: Build and Push Microservices
    runs-on: ubuntu-latest   #GitHub-hosted Ubuntu virtual machine
    strategy:
      matrix:  
        service: [result, vote, worker]  #it will all the serivce parallely
        include:
          - service: result  
            context: ./result  #identify docker files
            image_name: result
          - service: vote
            context: ./vote
            image_name: vote
          - service: worker
            context: ./worker
            image_name: worker

    steps:
    - uses: actions/checkout@v4

    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Get ACR Admin Password  #fetching cred dynamiclly
      id: acrpass
      run: |
        PASS=$(az acr credential show \
          --name nitorAcrPoc1 \
          --query "passwords[0].value" -o tsv)
        echo "ACR_PASS=$PASS" >> $GITHUB_ENV 

    - name: Docker Login to ACR
      run: |
        echo "$ACR_PASS" | docker login nitorAcrPoc1.azurecr.io \
          -u nitorAcrPoc1 \
          --password-stdin  
  
    - name: Build and push Docker images
      uses: docker/build-push-action@v6
      with:
        context: ${{ matrix.context }}
        push: true
        tags: nitorAcrPoc1.azurecr.io/${{ matrix.image_name }}:${{ github.run_number }}

  # --- Job 2: Deploy to AKS ---
  deploy:
    name: Deploy to AKS
    runs-on: ubuntu-latest
    needs: build  # Ye job tabhi chalegi jab build job success hogi

    defaults:
      run:
        shell: bash
        working-directory: ./k8s-manifest
    
    steps:
    - uses: actions/checkout@v4

    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Set AKS Context
      uses: azure/aks-set-context@v3
      with:
        resource-group: "rg_poc_1"
        cluster-name: "nitorAksPoc1"

    - name: Deploy to AKS
      run: |
        # Variables set kar rahe hain jo YAML templates mein use honge

        export IMAGE_TAG=${{ github.run_number }}
        export REGISTRY=nitorAcrPoc1.azurecr.io

        # Envsubst se variables replace karke apply kar rahe hain

        envsubst < redis-deployment.yaml | kubectl apply -f -
        envsubst < db-deployment.yaml | kubectl apply -f -
        envsubst < result-deployment.yaml | kubectl apply -f -
        envsubst < vote-deployment.yaml | kubectl apply -f -
        envsubst < worker-deployment.yaml | kubectl apply -f -
